### PR TITLE
database error information

### PR DESCRIPTION
**Pull request by zussel**
added a database error exception class which is used for database errors in all backends. This class consists of all available error informations of the backend throwing the error.

### CODE REVIEW

**Comment by suisou** [comment]
I have download this branch and compile it .this warning showed. 

In file included from /home/suisou/matador/test/orm/../person.hpp:5,
                 from /home/suisou/matador/test/orm/OrmTestUnit.cpp:7:
/home/suisou/matador/include/matador/utils/identifier.hpp: In member function â€˜matador::object_proxy* matador::object_store::insert(matador::object_proxy*, bool) [with T = demo::person]â€™:
/home/suisou/matador/include/matador/utils/identifier.hpp:220:23: warning: â€˜valâ€™ may be used uninitialized in this function [-Wmaybe-uninitialized]
   void value(T val) { id_ = val; }
                       ^~~
In file included from /home/suisou/matador/include/matador/object/object_store.hpp:34,
                 from /home/suisou/matador/include/matador/orm/persistence.hpp:23,
                 from /home/suisou/matador/test/orm/OrmTestUnit.cpp:10:
/home/suisou/matador/include/matador/utils/identifier_setter.hpp:52:7: note: â€ valâ€™ was declared here
     V val;
       ^~~

**Comment by zussel** [comment]
I don't get these warnings with gcc 9.2. I've set up a CentOS 8 Stream environment with mysql without this warning. Can you tell mir your exact setup (os, compiler). But I've initialized the values. Update the branch and check it again.

Btw.: The demo test doesn't fail anymore with mysql 8.

**Comment by suisou** [comment]
I have&nbsp; &nbsp;downloaded it&nbsp; marked with "&nbsp;initialized identifier value".&nbsp;
compile it again ,the warning disappear.


&nbsp;my ENV:centos 8 stream x64 ,gcc 8.2&nbsp;&nbsp;


[suisou@localhost build]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.2.1 20180905 (Red Hat 8.2.1-3) (GCC)
[suisou@localhost build]$



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sascha Kühl"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月6日(星期一) 晚上9:33
收件人:&nbsp;"zussel/matador"<matador@noreply.github.com&gt;;
抄送:&nbsp;"suisou"<552524615@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [zussel/matador] database error information (#113)




I don't get these warnings with gcc 9.2. I've set up a CentOS 8 Stream environment with mysql without this warning. Can you tell mir your exact setup (os, compiler). But I've initialized the values. Update the branch and check it again.
 
Btw.: The demo test doesn't fail anymore with mysql 8.

**Comment by zussel** [comment]
Thanks for your infos and good to see that the warnings have disappeared.

Can you confirm that the test from #111 is running with this branch?

**Comment by suisou** [comment]
I have confirmed that #111 have solved!
thank you.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sascha Kühl"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月6日(星期一) 晚上9:44
收件人:&nbsp;"zussel/matador"<matador@noreply.github.com&gt;;
抄送:&nbsp;"suisou"<552524615@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [zussel/matador] database error information (#113)




Thanks for your infos and good to see that the warnings have disappeared.
 
Can you confirm that the test from #111 is running with this branch?

**Comment by zussel** [comment]
Perfect! I'll add another test concerning `database_error`. Then the PR will be closed. And we come closer to version 0.6.2.

**Comment by suisou** [comment]
OK, I am wating for&nbsp; the new release .


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sascha Kühl"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月6日(星期一) 晚上10:01
收件人:&nbsp;"zussel/matador"<matador@noreply.github.com&gt;;
抄送:&nbsp;"suisou"<552524615@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [zussel/matador] database error information (#113)




Perfect! I'll add another test concerning database_error. Then the PR will be closed. And we come closer to version 0.6.2.

**Pull request merged**
